PRICE_MIN = 1
LIQUIDITY_MIN = 1_000_000

VOLUME_MULTIPLIER = 1.2

RESISTANCE_LOOKBACK = 20
VOLUME_LOOKBACK = 20

TOUCH_TOLERANCE = 0.01

# --- CONSOLIDATION ---
CONSOLIDATION_LOOKBACK = 10
MAX_RANGE_PERCENT = 0.03

# --- ELITE FEATURES ---
ATR_LOOKBACK = 14
COMPRESSION_THRESHOLD = 0.7